"""empty message

Revision ID: 1cd88c878a68
Revises: 4b319444f97b
Create Date: 2015-04-07 23:22:05.814000

"""

# revision identifiers, used by Alembic.
revision = '1cd88c878a68'
down_revision = '4b319444f97b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
