"""empty message

Revision ID: 350b88a0342b
Revises: 1568eef8e559
Create Date: 2015-04-12 19:24:19.645000

"""

# revision identifiers, used by Alembic.
revision = '350b88a0342b'
down_revision = '1568eef8e559'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
