""" test 

Revision ID: 381aa3a692bd
Revises: 564a62bbe10e
Create Date: 2015-03-30 23:47:54.235000

"""

# revision identifiers, used by Alembic.
revision = '381aa3a692bd'
down_revision = '564a62bbe10e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
