"""empty message

Revision ID: 3f52b46f60f3
Revises: 83bcb2f59f4
Create Date: 2015-04-07 23:17:58.870000

"""

# revision identifiers, used by Alembic.
revision = '3f52b46f60f3'
down_revision = '83bcb2f59f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
