"""empty message

Revision ID: 3fb08e12ef97
Revises: 198c858cf7b2
Create Date: 2015-04-05 23:31:13.407000

"""

# revision identifiers, used by Alembic.
revision = '3fb08e12ef97'
down_revision = '198c858cf7b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
