"""empty message

Revision ID: 455417b76586
Revises: 4f4b8444f241
Create Date: 2015-04-06 23:38:52.913000

"""

# revision identifiers, used by Alembic.
revision = '455417b76586'
down_revision = '4f4b8444f241'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
