"""empty message

Revision ID: 4b319444f97b
Revises: 3f52b46f60f3
Create Date: 2015-04-07 23:21:00.889000

"""

# revision identifiers, used by Alembic.
revision = '4b319444f97b'
down_revision = '3f52b46f60f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
