"""empty message

Revision ID: 4f4b8444f241
Revises: 4009ba130f7a
Create Date: 2015-04-06 23:36:56.011000

"""

# revision identifiers, used by Alembic.
revision = '4f4b8444f241'
down_revision = '4009ba130f7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
