"""empty message

Revision ID: 5106880d9346
Revises: 5471549eb299
Create Date: 2015-04-08 06:59:49.308000

"""

# revision identifiers, used by Alembic.
revision = '5106880d9346'
down_revision = '5471549eb299'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
