"""empty message

Revision ID: 539050fbbb20
Revises: 5106880d9346
Create Date: 2015-04-08 07:04:05.912000

"""

# revision identifiers, used by Alembic.
revision = '539050fbbb20'
down_revision = '5106880d9346'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
