"""empty message

Revision ID: 5471549eb299
Revises: 1cd88c878a68
Create Date: 2015-04-08 06:51:37.575000

"""

# revision identifiers, used by Alembic.
revision = '5471549eb299'
down_revision = '1cd88c878a68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
