"""add the role in the roles

Revision ID: 564a62bbe10e
Revises: 23dd43edf649
Create Date: 2015-03-30 23:00:01.118000

"""

# revision identifiers, used by Alembic.
revision = '564a62bbe10e'
down_revision = '23dd43edf649'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(u'ix_roles_default', 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_roles_default', table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
