"""inital migration

Revision ID: 5a01bc2316e0
Revises: None
Create Date: 2015-03-21 20:11:20.701000

"""

# revision identifiers, used by Alembic.
revision = '5a01bc2316e0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
