"""empty message

Revision ID: 83bcb2f59f4
Revises: 455417b76586
Create Date: 2015-04-07 07:20:14.307000

"""

# revision identifiers, used by Alembic.
revision = '83bcb2f59f4'
down_revision = '455417b76586'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
